@startuml "GOLD"
skinparam groupInheritance 2

together {
    abstract Assessment
    abstract Staging
    class "UICC TNM" as TNM <<Observation>>
    class "UICC TNM Residual Tumor Classification" as ResidualTumorClassification <<Observation>> 
    abstract Grading
    class "Histopathological Tumor Grading WHO" as HistopathologischesGrading <<Observation>>
    class "Tumor Disorder" as Tumorerkrankung <<Condition>>
    class ImagingStudy
}

together {
    abstract Therapie
    class MedikamentöseTherapie
}

together {
    ' class Patient
    class "Vital Signs Base" as Vitalstatus <<Observation>> 
    abstract Körpermaße
    class "Body Height" as Körpergröße <<Observation>> 
    class "Body Weight" as Körpergewicht <<Observation>>
}

together {
    class Laborbefund <<DiagnosticReport>>
    class Laborparameter <<Observation>>
    class Probe <<Specimen>>
    class Lesion <<BodyStructure>>
}

together {
    class EpisodeOfCare
    class Encounter
}

class Patient {
    Name
    name : HumanName
    ..
    GeschlechtAdministrativ
    gender : code
    ..
    Geburtsdatum
    birthDate : date
    ..
    Adresse
    address : Address
    ..
    Ethnizität
    extension : CodeableConcept
    ..
    GeschlechtBiologisch
    extension : CodeableConcept
}

class Vitalstatus {
    Verstorben: boolean
    Todeszeitpunkt: dateTime
    Todesursache: CodeableConcept
}

abstract Körpermaße {}

class Körpergröße {
    Messzeitpunkt : dateTime
    Messwert : Quantity
}

class Körpergewicht {
    Messzeitpunkt : dateTime
    Messwert : Quantity
}

class Tumorerkrankung {
    Diagnose ID
    id : id
    ..
    Klinischer Status
    clinicalStatus : CodeableConcept

    ..
    Diagnosesicherheit
    verificationStatus : CodeableConcept
    ..
    Diagnosecode
    code : CodeableConcept
    ..
    KlinischRelevanterZeitraum
    onset : Period
    ..
    Dokumentationsdatum
    recordedDate : dateTime
}

class RecistObservation <<Observation>> {
    code : CodeableConcept
    valueCodeableConcept : CodeableConcept
    effectiveDateTime : dateTime
}

class Laborbefund <<DiagnosticReport>> {
    ID : Identifier
}

class ImagingStudy{}

class Laborparameter <<Observation>> {
    Code : CodeableConcept
    Laborwert : Quantity
    Messzeitpunkt : dateTime
    Referenzbereich : Quantity
}

class Probe <<Specimen>> {
    ID : Identifier
    Probenart : CodeableConcept
    Entnahmestelle : CodeableConcept
}

abstract Assessment {}
abstract Staging {}
abstract Grading {}

class TNM {
    y : CodeableConcept
    r : CodeableConcept
    a : CodeableConcept
    T : CodeableConcept
    m : CodeableConcept
    N : CodeableConcept
    M : CodeableConcept
    L : CodeableConcept
    V : CodeableConcept
    Pn : CodeableConcept
    S : CodeableConcept
    numberOfNodesAffected : Quantity
    numberOfNodesExamined : Quantity
}

class ResidualTumorClassification {
    R : CodeableConcept
}

class HistopathologischesGrading <<Observation>> {
    Grade : CodeableConcept
}

abstract Therapie {}

class Prozedur <<Procedure>> {
    Code: CodeableConcept
    Durchführungsdatum: dateTime
    Dokumentationsdatum: dateTime
    Körperstelle: CodeableConcept
}


class MedikamentöseTherapie <<MedicationStatement>> {
    Wirkstoff: CodeableConcept
    TherapieBeginn: dateTime
    TherapieEnde: dateTime
    TherapieIntention: CodeableConcept
}

class "ECOG Performance Status" as ECOG <<Observation>> {}
class "Karnofsky Performance Status" as Karnofsky <<Observation>> {}
class Lesion <<BodyStructure>> {}
class EpisodeOfCare {}
class Encounter {}


Vitalstatus --> Patient : subject
Körpergröße --* Körpermaße
Körpermaße --> Patient : subject
Körpergewicht --* Körpermaße
Tumorerkrankung --> ImagingStudy : evidence.detail
Tumorerkrankung --> Patient : subject
Tumorerkrankung --> Tumorerkrankung : "ocurredFollowing"
Tumorerkrankung --> Assessment : stage.assessment
RecistObservation --> Patient : subject
RecistObservation --> ImagingStudy : partOf
RecistObservation --> Therapie : partOf
Laborbefund --> Patient : subject
Laborbefund --> Laborparameter : result
Laborparameter --> Probe : specimen
Staging --* Assessment
Grading --* Assessment
TNM --* Staging
TNM --> ResidualTumorClassification : hasMember
HistopathologischesGrading --* Grading
HistopathologischesGrading --> Probe : specimen
Therapie --> Patient : subject
Prozedur --* Therapie
MedikamentöseTherapie --* Therapie
ECOG --> Patient : subject
Karnofsky --> Patient : subject
Lesion --> Patient : subject
Probe --> Lesion : Extension
Probe --> Patient : subject
Laborparameter --> Lesion : focus
Laborbefund --> Probe : specimen
Encounter --> EpisodeOfCare : episodeOfCare
EpisodeOfCare --> Tumorerkrankung : diagnosis.condition
TNM --> EpisodeOfCare : Extension
TNM --> Encounter : encounter
Laborbefund --> Encounter : Extension
Laborbefund --> Tumorerkrankung : Extension
Prozedur --> Laborbefund : reasonReference

@enduml