@startuml "GOLD"
skinparam groupInheritance 2

class Patient <<Patient>> {
    Name
    name : HumanName
    ..
    GeschlechtAdministrativ
    gender : code
    ..
    Geburtsdatum
    birthDate : date
    ..
    Adresse
    address : Address
    ..
    Ethnizität
    extension : CodeableConcept
    ..
    GeschlechtBiologisch
    extension : CodeableConcept
}

class Vitalstatus <<Observation>> {
    Verstorben: boolean
    Todeszeitpunkt: dateTime
    Todesursache: CodeableConcept
}

Vitalstatus --> Patient : subject

abstract Körpermaße {

}

Körpermaße --> Patient : subject

class Körpergröße <<Observation>> {
    Messzeitpunkt : dateTime
    Messwert : Quantity
}

Körpergröße --* Körpermaße

class Körpergewicht <<Observation>> {
    Messzeitpunkt : dateTime
    Messwert : Quantity
}

Körpergewicht --* Körpermaße

class Tumorerkrankung <<Condition>> {
    Diagnose ID
    id : id
    ..
    Klinischer Status
    clinicalStatus : CodeableConcept
    ..
    Diagnosesicherheit
    verificationStatus : CodeableConcept
    ..
    Diagnosecode
    code : CodeableConcept
    ..
    KlinischRelevanterZeitraum
    onset : Period
    ..
    Dokumentationsdatum
    recordedDate : dateTime
}

Tumorerkrankung --> ImagingStudy : evidence.detail
Tumorerkrankung --> Patient : subject
Tumorerkrankung --> Tumorerkrankung : "ocurredFollowing"
Tumorerkrankung --> Assessment : stage.assessment

class RecistObservation <<Observation>> {
    code : CodeableConcept
    valueCodeableConcept : CodeableConcept
    effectiveDateTime : dateTime
}

RecistObservation --> Patient : subject
RecistObservation --> ImagingStudy : partOf
RecistObservation --> Therapie : partOf

class Laborbefund <<DiagnosticReport>> {
    ID : Identifier
}

Laborbefund --> Patient : subject
Laborbefund --> Laborparameter : result

class ImagingStudy <<ImagingStudy>> {

}


class Laborparameter <<Observation>> {
    Code : CodeableConcept
    Laborwert : Quantity
    Messzeitpunkt : dateTime
    Referenzbereich : Quantity
}

Laborparameter --> Probe : specimen

class Probe <<Specimen>> {
    ID : Identifier
    Probenart : CodeableConcept
    Entnahmestelle : CodeableConcept
}

abstract Assessment {

}

Assessment *-- Staging
Assessment *-- Grading

abstract Staging {

}

Staging *-- TNM

abstract Grading {

}

Grading *-- HistopathologischesGrading

class TNM <<Observation>> {
    y : CodeableConcept
    r : CodeableConcept
    a : CodeableConcept
    T : CodeableConcept
    m : CodeableConcept
    N : CodeableConcept
    M : CodeableConcept
    L : CodeableConcept
    V : CodeableConcept
    Pn : CodeableConcept
    S : CodeableConcept
    numberOfNodesAffected : Quantity
    numberOfNodesExamined : Quantity
}

TNM --> ResidualTumorClassification : hasMember

class ResidualTumorClassification <<Observation>> {
    R : CodeableConcept
}


class HistopathologischesGrading <<Observation>> {
    Grade : CodeableConcept
}

HistopathologischesGrading --> Probe : specimen

abstract Therapie {

}

Therapie --> Patient : subject

class Prozedur <<Procedure>> {
    Code: CodeableConcept
    Durchführungsdatum: dateTime
    Dokumentationsdatum: dateTime
    Körperstelle: CodeableConcept
}

Prozedur --* Therapie

class MedikamentöseTherapie <<MedicationStatement>> {
    Wirkstoff: CodeableConcept
    TherapieBeginn: dateTime
    TherapieEnde: dateTime
    TherapieIntention: CodeableConcept
}

MedikamentöseTherapie --* Therapie

@enduml