@startuml "GOLD"
skinparam groupInheritance 2

class Patient <<Patient>> {
    Name
    name : HumanName
    ..
    GeschlechtAdministrativ
    gender : code
    ..
    Geburtsdatum
    birthDate : date
    ..
    Adresse
    address : Address
    ..
    Ethnizität
    extension : CodeableConcept
    ..
    GeschlechtBiologisch
    extension : CodeableConcept
}

class Vitalstatus <<Observation>> {
    Verstorben: boolean
    Todeszeitpunkt: dateTime
    Todesursache: CodeableConcept
}

Patient <-- Vitalstatus : subject

abstract Körpermaße {

}

Patient <-- Körpermaße : subject

class Körpergröße <<Observation>> {
    Messzeitpunkt : dateTime
    Messwert : Quantity
}

Körpermaße *-- Körpergröße

class Körpergewicht <<Observation>> {
    Messzeitpunkt : dateTime
    Messwert : Quantity
}

Körpermaße *-- Körpergewicht

class Diagnose <<Condition>> {
    Diagnose ID
    id : id
    ..
    Klinischer Status
    clinicalStatus : CodeableConcept
    ..
    Diagnosesicherheit
    verificationStatus : CodeableConcept
    ..
    Diagnosecode
    code : CodeableConcept
    ..
    KlinischRelevanterZeitraum
    onset : Period
    ..
    Dokumentationsdatum
    recordedDate : dateTime
}

Patient <-- Diagnose : subject
Diagnose <-- Diagnose : "relatedTo"

class RecistObservation <<Observation>> {
    code : CodeableConcept
    valueCodeableConcept : CodeableConcept
    effectiveDateTime : dateTime
}



class Laborbefund <<DiagnosticReport>> {
    ID : Identifier
}

Patient <-- Laborbefund : subject

class Laborparameter <<Observation>> {
    Code : CodeableConcept
    Laborwert : Quantity
    Messzeitpunkt : dateTime
    Referenzbereich : Quantity
}

class Probe <<Specimen>> {
    ID : Identifier
    Probenart : CodeableConcept
    Entnahmestelle : CodeableConcept
}

Laborbefund --> Laborparameter : result
Laborparameter --> Probe : specimen

abstract Assessment {

}

abstract Staging {

}

abstract Grading {

}

class TNM <<Observation>> {
    y : CodeableConcept
    r : CodeableConcept
    a : CodeableConcept
    T : CodeableConcept
    m : CodeableConcept
    N : CodeableConcept
    M : CodeableConcept
    L : CodeableConcept
    V : CodeableConcept
    Pn : CodeableConcept
    S : CodeableConcept
    numberOfNodesAffected : Quantity
    numberOfNodesExamined : Quantity
}

class ResidualTumorClassification <<Observation>> {
    R : CodeableConcept
}

TNM --> ResidualTumorClassification : hasMember

class HistopathologischesGrading <<Observation>> {
    Grade : CodeableConcept
}

Assessment *-- Staging
Assessment *-- Grading
Staging *-- TNM
Grading *-- HistopathologischesGrading
Diagnose --> Assessment : stage.assessment
HistopathologischesGrading --> Probe : specimen

abstract Therapie {

}

class Prozedur <<Procedure>> {
    Code: CodeableConcept
    Durchführungsdatum: dateTime
    Dokumentationsdatum: dateTime
    Körperstelle: CodeableConcept
}

Therapie *-- Prozedur

class MedikamentöseTherapie <<MedicationStatement>> {
    Wirkstoff: CodeableConcept
    TherapieBeginn: dateTime
    TherapieEnde: dateTime
    TherapieIntention: CodeableConcept
}

Therapie *-- MedikamentöseTherapie
Patient <-- Therapie : subject

class ClinicalStudy <<ResearchStudy>> {
    identifier : Identifier
    title : string
    protocol : Reference
    partOf : Reference
    status : code 
    primaryPurposeType : CodeableConcept
    phase : CodeableConcept
    category : CodeableConcept
    focus : CodeableConcept
    condition : CodeableConcept
    contact : ContactDetail
    relatedArtifact : RelatedArtifact
    keyword : CodeableConcept
    location : CodeableConcept
    description : text
    enrollment : Reference 
    period : Period
    sponsor : Reference
    principalInvestigator : Reference
    site : Reference
    reasonStopped : CodeableConcept
    note : Annotation
    armName : string
    armType : CodeableConcept
    armDescription : string
    objectiveName : string
    objectiveType : CodeableConcept
}

abstract PrincipalInvestigator 
class Practitioner <<Practitioner>> {

}

class PractionerRole <<PractionerRole>> {

}

Practitioner --* PrincipalInvestigator
PractionerRole --* PrincipalInvestigator

class Organization <<Organization>> {

}

class Group <<Group>> {

}

class PlanDefinition <<PlanDefinition>> {

}

ClinicalStudy::sponsor --> Organization
ClinicalStudy::enrollment --> Group
ClinicalStudy::protocol --> PlanDefinition
ClinicalStudy::partOf --> ClinicalStudy

@enduml